#! /bin/sh
IPTABLES=iptables
RULESFILE="/etc/firewall.rules"

usage() {
	echo Usage
	echo
	echo 'fw-script [OPTION]...'
	echo 
	echo OPTIONS:
	echo '-6, --ipv6           Use ip6tables'
	echo '-v, --verbose        Display executed iptables commands'
	echo '-h, --help           Display this text and exit'
	echo
	exit
}

TEMP=`getopt -o vh6 --long verbose,help,ipv6 -n 'fw-script' -- "$@"`
eval set -- "$TEMP"

while true ; do
	case "$1" in
		-6|--ipv6) IPTABLES="ip6tables"; 
			RULESFILE="/etc/firewall6.rules"
			shift ;;
		-v|--verbose) VERBOSE="1"; shift ;;
		-h|--help) usage; shift ;;
		--) shift ; break;;
		*) echo "ERROR!"; exit 1 ;;
	esac
done

if [ ! -f $RULESFILE ]; then
	echo "Rules file: $RULESFILE not found!"
	exit 1;
fi

# Feed in and replace rules
RULES=`sed -e '
s/#.*//				# Remove comments
/\\\/N				# Join lines ending with backslash

s/\$SNEW/-m state --state NEW/	# Replace macros
s/\$TCP/-p tcp --dport/
s/\$UDP/-p udp --dport/
s/\$ICMPV6/-p icmpv6 --icmpv6-type/
s/\$ICMP/-p icmp --icmp-type/
s/\$MTCP/-p tcp -m multiport --dports/
s/\$MUDP/-p udp -m multiport --dports/
s/\$NAT/-t nat/
s/\$SNAT/-t nat -j SNAT --to/
s/\$DNAT/-t nat -j DNAT --to/

s/\\\\\n/_/g			# Replace newlines with underscores
s/[	 ]\+/_/g		# Replace whitespaces with underscores

' $RULESFILE`

for i in $RULES; do
	LINE=`echo $i| sed -e 's/_/ /g'`
	if [ "$VERBOSE" == "1" ]; then echo $IPTABLES $LINE; fi
	$IPTABLES $LINE
done
