#! /bin/sh
RULESFILE="/etc/firewall.rules"

TEMP=`getopt -o v --long verbose -n 'fw-script' -- "$@"`
eval set -- "$TEMP"

while true ; do
	case "$1" in
		-v|--verbose) VERBOSE="1"; shift ;;

		--) shift ; break;;
		*) echo "ERROR!"; exit 1 ;;
	esac
done

if [ ! -f $RULESFILE ]; then
	echo "Rules file: $RULESFILE not found!"
	exit 1;
fi

# Feed in and replace rules
RULES=`sed -e '
s/$SNEW/-m state --state NEW/g
s/$FWD/FORWARD/g
s/$TCP/-p tcp --dport/g
s/$UDP/-p udp --dport/g
s/$SNAT/-t nat -j SNAT --to/g
s/$DNAT/-t nat -j DNAT --to/g


s/#.*//
/\\\/N
s/\\\\\n/_/g
s/[	 ]\+/_/g
' $RULESFILE`

for i in $RULES; do
	LINE=`echo $i| sed -e 's/_/ /g'`
	if [ "$VERBOSE" == "1" ]; then echo iptables $LINE; fi
	#iptables $LINE
done
